// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlA5Kq0QlMZ9OfK1lnxDYdUDjLsOzxYAU',
    appId: '1:927491863900:web:8a027303707b08c6bb7d99',
    messagingSenderId: '927491863900',
    projectId: 'advanced-chat-app-372b6',
    authDomain: 'advanced-chat-app-372b6.firebaseapp.com',
    storageBucket: 'advanced-chat-app-372b6.appspot.com',
    measurementId: 'G-JNMWM2Z8JC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC99JM5lcNblcaTPO2TnfFMYsaEIfUq3Bc',
    appId: '1:927491863900:android:ac4e354e84e5f4dabb7d99',
    messagingSenderId: '927491863900',
    projectId: 'advanced-chat-app-372b6',
    storageBucket: 'advanced-chat-app-372b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBosssaWNMv9AOAwREnO6vKJPOcQLsM9bY',
    appId: '1:927491863900:ios:f6a4070f1d8f1e27bb7d99',
    messagingSenderId: '927491863900',
    projectId: 'advanced-chat-app-372b6',
    storageBucket: 'advanced-chat-app-372b6.appspot.com',
    iosClientId: '927491863900-uk24k1mb3o2f7tn1i279uougn1et9hib.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappadvanced',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBosssaWNMv9AOAwREnO6vKJPOcQLsM9bY',
    appId: '1:927491863900:ios:2cff4c10eddca64dbb7d99',
    messagingSenderId: '927491863900',
    projectId: 'advanced-chat-app-372b6',
    storageBucket: 'advanced-chat-app-372b6.appspot.com',
    iosClientId: '927491863900-2q11pcmtuqmbh0kbe3v1s8tb5tk177me.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatappadvanced.RunnerTests',
  );
}
